FROM ruby:2.6-alpine

RUN apk update && apk add -u alpine-sdk nodejs npm tzdata
RUN apk update && apk add -u postgresql-dev imagemagick yarn less

RUN gem install bundler
RUN gem install rails -v 6.0.0
RUN gem install nokogiri


WORKDIR /app
