ARG BASE_VERSION
FROM melvinsembrano/rails:${BASE_VERSION}-base

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk && \
  apk add glibc-2.29-r0.apk

RUN apk --no-cache add \
    chromium-chromedriver\
    zlib-dev \
    chromium \
    xvfb \
    wait4ports \
    xorg-server \
    dbus \
    ttf-freefont \
    mesa-dri-swrast \
    udev 

COPY ./scripts/test.sh /scripts/test.sh

CMD /scripts/test.sh
